import type { Product } from '../types';
import { Dietary } from '../types/enums';

// Extended Product type with category for menu display
export interface ProductWithCategory extends Product {
  Category: number;
}

// Mock product data - this will be replaced with real API data later
export const MOCK_PRODUCTS: ProductWithCategory[] = [
  // Pizzas (Category 0)
  {
    Id: '1',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Margherita Pizza","fi":"Margherita Pizza","sv":"Margherita Pizza"}',
    Description: '{"en":"Classic pizza with tomato sauce, mozzarella, and fresh basil","fi":"Klassinen pizza tomaattikastikkeella, mozzarellalla ja tuoreella basilikalla","sv":"Klassisk pizza med tomatsås, mozzarella och färsk basilika"}',
    Price: 12.99,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, fresh basil, olive oil, salt","fi":"jauho, tomaattikastike, mozzarellajuusto, tuore basilika, oliiviöljy, suola","sv":"mjöl, tomatsås, mozzarellaost, färsk basilika, olivolja, salt"}',
    Dietaries: [Dietary.Vegetarian, Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Cheese","fi":"Lisäjuusto","sv":"Extra Ost"},"PriceIncrement":1.50},{"Name":{"en":"Mushrooms","fi":"Sienet","sv":"Svamp"},"PriceIncrement":1.00},{"Name":{"en":"Olives","fi":"Oliivit","sv":"Oliver"},"PriceIncrement":0.75}]',
    FreeToppings: 1,
  },
  {
    Id: '2',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Pepperoni Pizza"}',
    Description: '{"en":"Pizza topped with spicy pepperoni and mozzarella cheese"}',
    Price: 14.99,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, pepperoni, olive oil, salt, pepper"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Pepperoni","fi":"Lisä Pepperoni","sv":"Extra Pepperoni"},"PriceIncrement":2.00},{"Name":{"en":"Jalapeños","fi":"Jalapeñot","sv":"Jalapeños"},"PriceIncrement":0.50},{"Name":{"en":"Extra Cheese","fi":"Lisäjuusto","sv":"Extra Ost"},"PriceIncrement":1.50}]',
    FreeToppings: 2,
  },
  {
    Id: '3',
    OrganizationId: 'mock-org-1',
    Name: '{"fi":"Havaiji Pizza"}',
    Description: '{"fi":"Pizza kinkkua, ananasta ja mozzarellaa"}',
    Price: 13.99,
    Ingredients: '{"fi":"jauho, tomaattikastike, mozzarellajuusto, kinkku, ananas, oliiviöljy, suola"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Ham","fi":"Lisäkinkku","sv":"Extra Skinka"},"PriceIncrement":2.00},{"Name":{"en":"Extra Pineapple","fi":"Lisäananas","sv":"Extra Ananas"},"PriceIncrement":1.00},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50}]',
    FreeToppings: 0,
  },
  {
    Id: '4',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Veggie Supreme","fi":"Kasvis Supreme","sv":"Veggie Supreme"}',
    Description: '{"en":"Loaded with fresh vegetables and mozzarella","fi":"Täynnä tuoreita vihanneksia ja mozzarellaa","sv":"Fylld med färska grönsaker och mozzarella"}',
    Price: 13.49,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, bell peppers, mushrooms, onions, olives, tomatoes, olive oil, salt","fi":"jauho, tomaattikastike, mozzarellajuusto, paprika, sienet, sipuli, oliivit, tomaatit, oliiviöljy, suola","sv":"mjöl, tomatsås, mozzarellaost, paprika, svamp, lök, oliver, tomater, olivolja, salt"}',
    Dietaries: [Dietary.Vegetarian, Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Veggies","fi":"Lisävihannekset","sv":"Extra Grönsaker"},"PriceIncrement":1.50},{"Name":{"en":"Vegan Cheese","fi":"Vegaanijuusto","sv":"Vegansk Ost"},"PriceIncrement":2.00},{"Name":{"en":"Garlic","fi":"Valkosipuli","sv":"Vitlök"},"PriceIncrement":0.50},{"Name":{"en":"Sun-dried Tomatoes","fi":"Auringonkuivatut tomaatit","sv":"Soltorkade Tomater"},"PriceIncrement":1.25}]',
    FreeToppings: 1,
  },
  {
    Id: '5',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"BBQ Chicken Pizza","fi":"BBQ Kana Pizza","sv":"BBQ Kyckling Pizza"}',
    Description: '{"en":"BBQ sauce, grilled chicken, red onions, and cilantro","fi":"BBQ-kastike, grillattu kana, punainen sipuli ja korianteri","sv":"BBQ-sås, grillad kyckling, rödlök och koriander"}',
    Price: 15.99,
    Ingredients: '{"en":"flour, BBQ sauce, mozzarella cheese, grilled chicken, red onions, cilantro, olive oil, salt","fi":"jauho, BBQ-kastike, mozzarellajuusto, grillattu kana, punainen sipuli, korianteri, oliiviöljy, suola","sv":"mjöl, BBQ-sås, mozzarellaost, grillad kyckling, rödlök, koriander, olivolja, salt"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Chicken","fi":"Lisäkana","sv":"Extra Kyckling"},"PriceIncrement":2.50},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50},{"Name":{"en":"Jalapeños","fi":"Jalapeñot","sv":"Jalapeños"},"PriceIncrement":0.75},{"Name":{"en":"Ranch Drizzle","fi":"Ranch-kastike","sv":"Ranch Sås"},"PriceIncrement":0.50}]',
    FreeToppings: 2,
  },
  {
    Id: '6',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Meat Lover\'s Pizza", "fi":"Äijävege Pizza", "sv":"Köttälskare Pizza"}',
    Description: '{"en":"Loaded with pepperoni, sausage, ham, and bacon","fi":"Täynnä pepperonia, makkaraa, kinkkua ja pekonia","sv":"Fylld med pepperoni, korv, skinka och bacon"}',
    Price: 16.99,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, pepperoni, sausage, ham, bacon, olive oil, salt","fi":"jauho, tomaattikastike, mozzarellajuusto, pepperoni, makkara, kinkku, pekoni, oliiviöljy, suola","sv":"mjöl, tomatsås, mozzarellaost, pepperoni, korv, skinka, bacon, olivolja, salt"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Pepperoni","fi":"Lisä Pepperoni","sv":"Extra Pepperoni"},"PriceIncrement":2.00},{"Name":{"en":"Ground Beef","fi":"Jauheliha","sv":"Nötfärs"},"PriceIncrement":2.00},{"Name":{"en":"Italian Sausage","fi":"Italialainen makkara","sv":"Italiensk Korv"},"PriceIncrement":2.00}]',
    FreeToppings: 1,
  },
  {
    Id: '38',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Fantasia Pizza - Build Your Own","fi":"Fantasia Pizza - Rakenna omasi","sv":"Fantasia Pizza - Bygg din egen"}',
    Description: '{"en":"Create your perfect pizza! Start with our classic base and add your favorite toppings","fi":"Luo täydellinen pizzasi! Aloita klassisella pohjalla ja lisää suosikkitäytteet","sv":"Skapa din perfekta pizza! Börja med vår klassiska bas och lägg till dina favorittoppings"}',
    Price: 11.99,
    Ingredients: '{"en":"flour, tomato sauce, mozzarella cheese, olive oil, salt","fi":"jauho, tomaattikastike, mozzarellajuusto, oliiviöljy, suola","sv":"mjöl, tomatsås, mozzarellaost, olivolja, salt"}',
    Dietaries: [Dietary.Vegetarian, Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
    Toppings: '[{"Name":{"en":"Extra Cheese","fi":"Lisäjuusto","sv":"Extra Ost"},"PriceIncrement":1.50},{"Name":{"en":"Mozzarella","fi":"Mozzarella","sv":"Mozzarella"},"PriceIncrement":1.50},{"Name":{"en":"Pepperoni","fi":"Pepperoni","sv":"Pepperoni"},"PriceIncrement":2.00},{"Name":{"en":"Italian Sausage","fi":"Italialainen makkara","sv":"Italiensk Korv"},"PriceIncrement":2.00},{"Name":{"en":"Ham","fi":"Kinkku","sv":"Skinka"},"PriceIncrement":2.00},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":2.00},{"Name":{"en":"Ground Beef","fi":"Jauheliha","sv":"Nötfärs"},"PriceIncrement":2.00},{"Name":{"en":"Grilled Chicken","fi":"Grillattu kana","sv":"Grillad Kyckling"},"PriceIncrement":2.50},{"Name":{"en":"Mushrooms","fi":"Sienet","sv":"Svamp"},"PriceIncrement":1.00},{"Name":{"en":"Bell Peppers","fi":"Paprika","sv":"Paprika"},"PriceIncrement":1.00},{"Name":{"en":"Red Onions","fi":"Punainen sipuli","sv":"Rödlök"},"PriceIncrement":0.75},{"Name":{"en":"Olives","fi":"Oliivit","sv":"Oliver"},"PriceIncrement":0.75},{"Name":{"en":"Tomatoes","fi":"Tomaatit","sv":"Tomater"},"PriceIncrement":0.75},{"Name":{"en":"Pineapple","fi":"Ananas","sv":"Ananas"},"PriceIncrement":1.00},{"Name":{"en":"Jalapeños","fi":"Jalapeñot","sv":"Jalapeños"},"PriceIncrement":0.75},{"Name":{"en":"Sun-dried Tomatoes","fi":"Auringonkuivatut tomaatit","sv":"Soltorkade Tomater"},"PriceIncrement":1.25},{"Name":{"en":"Spinach","fi":"Pinaatti","sv":"Spenat"},"PriceIncrement":1.00},{"Name":{"en":"Arugula","fi":"Rucola","sv":"Ruccola"},"PriceIncrement":1.00},{"Name":{"en":"Basil","fi":"Basilika","sv":"Basilika"},"PriceIncrement":0.50},{"Name":{"en":"Garlic","fi":"Valkosipuli","sv":"Vitlök"},"PriceIncrement":0.50}]',
    FreeToppings: 3,
  },
  // Burgers (Category 1)
  {
    Id: '7',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Classic Burger","fi":"Klassikkoburger","sv":"Klassisk burgare"}',
    Description: '{"en":"Beef patty with lettuce, tomato, onion, and pickles","fi":"Naudanliha pihvi salaatilla, tomaatilla, sipulilla ja suolakurkulla","sv":"Nötköttsburgare med sallad, tomat, lök och pickles"}',
    Price: 9.99,
    Ingredients: '{"en":"wheat flour, beef, lettuce, tomato, onion, pickles, sesame seeds, salt, pepper","fi":"vehnäjauho, naudanliha, salaatti, tomaatti, sipuli, suolakurkku, seesaminsiemenet, suola, pippuri","sv":"vetemjöl, nötkött, sallad, tomat, lök, pickles, sesamfrön, salt, peppar"}',
    Dietaries: [Dietary.LactoseFree],
    ImgUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
    Toppings: '[{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50},{"Name":{"en":"Extra Cheese","fi":"Lisäjuusto","sv":"Extra Ost"},"PriceIncrement":1.00},{"Name":{"en":"Fried Egg","fi":"Paistettu muna","sv":"Stekt Ägg"},"PriceIncrement":1.25},{"Name":{"en":"Avocado","fi":"Avokado","sv":"Avokado"},"PriceIncrement":2.00}]',
    Excludables: '[{"en":"Lettuce","fi":"Salaatti","sv":"Sallad"},{"en":"Tomato","fi":"Tomaatti","sv":"Tomat"},{"en":"Onion","fi":"Sipuli","sv":"Lök"},{"en":"Pickles","fi":"Suolakurkku","sv":"Pickles"}]',
  },
  {
    Id: '8',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Cheese Burger","fi":"Juustoburger","sv":"Ostburgare"}',
    Description: '{"en":"Double beef patty with melted cheese","fi":"Kaksois naudanliha pihvi sulatetulla juustolla","sv":"Dubbel nötköttsburgare med smält ost"}',
    Price: 10.99,
    Ingredients: '{"en":"wheat flour, beef, cheddar cheese, lettuce, tomato, onion, sesame seeds, salt, pepper, milk","fi":"vehnäjauho, naudanliha, cheddarjuusto, salaatti, tomaatti, sipuli, seesaminsiemenet, suola, pippuri, maito","sv":"vetemjöl, nötkött, cheddarost, sallad, tomat, lök, sesamfrön, salt, peppar, mjölk"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
    Toppings: '[{"Name":{"en":"Extra Patty","fi":"Lisäpihvi","sv":"Extra Biff"},"PriceIncrement":3.00},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":1.50},{"Name":{"en":"Onion Rings","fi":"Sipulirenkaat","sv":"Lökringa"},"PriceIncrement":1.75}]',
    Excludables: '[{"en":"Cheese","fi":"Juusto","sv":"Ost"},{"en":"Lettuce","fi":"Salaatti","sv":"Sallad"},{"en":"Tomato","fi":"Tomaatti","sv":"Tomat"},{"en":"Onion","fi":"Sipuli","sv":"Lök"}]',
  },
  {
    Id: '9',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Bacon Burger"}',
    Description: '{"en":"Burger with crispy bacon and BBQ sauce"}',
    Price: 11.99,
    Ingredients: '{"en":"wheat flour, beef, bacon, cheddar cheese, lettuce, tomato, BBQ sauce, sesame seeds, salt, pepper, milk"}',
    Dietaries: [Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
    Toppings: '[{"Name":{"en":"Extra Bacon","fi":"Lisäpekoni","sv":"Extra Bacon"},"PriceIncrement":2.00},{"Name":{"en":"Cheddar Cheese","fi":"Cheddarjuusto","sv":"Cheddarost"},"PriceIncrement":1.00},{"Name":{"en":"Caramelized Onions","fi":"Karamellisoitu sipuli","sv":"Karamelliserad Lök"},"PriceIncrement":1.25},{"Name":{"en":"Mushrooms","fi":"Sienet","sv":"Svamp"},"PriceIncrement":1.00}]',
    Excludables: '[{"en":"Bacon"},{"en":"Cheese"},{"en":"Lettuce"},{"en":"Tomato"},{"en":"BBQ Sauce"}]',
  },
  // Sides (Category 2)
  {
    Id: '10',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"French Fries","fi":"Ranskalaiset","sv":"Pommes Frites"}',
    Description: '{"en":"Crispy golden french fries","fi":"Rapeat kultaiset ranskalaiset","sv":"Krispiga gyllene pommes frites"}',
    Price: 4.99,
    Ingredients: '{"en":"potatoes, vegetable oil, salt","fi":"perunat, kasviöljy, suola","sv":"potatis, vegetabilisk olja, salt"}',
    Dietaries: [Dietary.GlutenFree, Dietary.LactoseFree, Dietary.Vegan],
    ImgUrl: 'https://images.unsplash.com/photo-1630384082554-e4e5c0e7b869?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
    Toppings: '[{"Name":{"en":"Cheese Sauce","fi":"Juustokastike","sv":"Ostsås"},"PriceIncrement":1.50},{"Name":{"en":"Bacon Bits","fi":"Pekonipalat","sv":"Baconbitar"},"PriceIncrement":1.00},{"Name":{"en":"Truffle Oil","fi":"Tryffelijöljy","sv":"Tryffelolja"},"PriceIncrement":2.00},{"Name":{"en":"Chili Flakes","fi":"Chililhiutaleet","sv":"Chiliflingor"},"PriceIncrement":0.25}]',
  },
  {
    Id: '11',
    OrganizationId: 'mock-org-1',
    Name: '{"fi":"Sipulirenkaat"}',
    Description: '{"fi":"Rapeat panetoidut sipulirenkaat"}',
    Price: 5.49,
    Ingredients: '{"fi":"sipuli, vehnäjauho, panko, munat, maito, kasviöljy, suola"}',
    Dietaries: [Dietary.Vegetarian, Dietary.LowLactose],
    ImgUrl: 'https://images.unsplash.com/photo-1619221882783-4f9a5e2e3ee9?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
  },
  {
    Id: '12',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Mozzarella Sticks","fi":"Mozzarella Tikut","sv":"Mozzarella Pinnar"}',
    Description: '{"en":"Breaded mozzarella sticks with marinara sauce","fi":"Panetoidut mozzarella tikut marinara kastikkeella","sv":"Panerade mozzarella pinnar med marinara sås"}',
    Price: 6.99,
    Ingredients: '{"en":"mozzarella cheese, wheat flour, breadcrumbs, eggs, milk, vegetable oil, salt","fi":"mozzarellajuusto, vehnäjauho, korppujauho, munat, maito, kasviöljy, suola","sv":"mozzarellaost, vetemjöl, ströbröd, ägg, mjölk, vegetabilisk olja, salt"}',
    Dietaries: [Dietary.Vegetarian],
    ImgUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
    Toppings: '[{"Name":{"en":"Ranch Dip","fi":"Ranch-dippi","sv":"Ranch Dip"},"PriceIncrement":0.50},{"Name":{"en":"Garlic Aioli","fi":"Valkosipuli-aioli","sv":"Vitlöksaioli"},"PriceIncrement":0.75},{"Name":{"en":"Spicy Mayo","fi":"Tulinen majoneesi","sv":"Kryddmajonnäs"},"PriceIncrement":0.50}]',
  },
  // Drinks (Category 3)
  {
    Id: '13',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Coca-Cola"}',
    Description: '{"en":"Classic Coca-Cola"}',
    Price: 2.99,
    Ingredients: '{"en":"carbonated water, sugar, caffeine, phosphoric acid, natural flavors"}',
    ImgUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  {
    Id: '14',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Sprite","fi":"Sprite","sv":"Sprite"}',
    Description: '{"en":"Refreshing lemon-lime soda","fi":"Virkistävä sitruuna-limejuoma","sv":"Förfriskande citron-lime läsk"}',
    Price: 2.99,
    Ingredients: '{"en":"carbonated water, sugar, citric acid, natural lemon-lime flavor","fi":"hiilihapotettu vesi, sokeri, sitruunahappo, luonnollinen sitrus-limu aromi","sv":"kolsyrat vatten, socker, citronsyra, naturlig citron-lime smak"}',
    ImgUrl: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  {
    Id: '15',
    OrganizationId: 'mock-org-1',
    Name: '{"fi":"Appelsiinimehu"}',
    Description: '{"fi":"Tuorepuristettu appelsiinimehu"}',
    Price: 3.49,
    Ingredients: '{"fi":"appelsiini"}',
    ImgUrl: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  // Alcoholic Beverages
  {
    Id: '16',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Cabernet Sauvignon 6cl","fi":"Cabernet Sauvignon 6cl","sv":"Cabernet Sauvignon 6cl"}',
    Description: '{"en":"Red wine - Rich and full-bodied","fi":"Punaviini - Täyteläinen ja runsas","sv":"Rödvin - Fylligt och kraftfullt"}',
    Price: 5.50,
    Ingredients: '{"en":"red grapes, sulfites","fi":"punaviinirypäleet, sulfiitit","sv":"röda druvor, sulfiter"}',
    ImgUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
  {
    Id: '17',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Cabernet Sauvignon 12cl","fi":"Cabernet Sauvignon 12cl","sv":"Cabernet Sauvignon 12cl"}',
    Description: '{"en":"Red wine - Rich and full-bodied","fi":"Punaviini - Täyteläinen ja runsas","sv":"Rödvin - Fylligt och kraftfullt"}',
    Price: 9.50,
    Ingredients: '{"en":"red grapes, sulfites","fi":"punaviinirypäleet, sulfiitit","sv":"röda druvor, sulfiter"}',
    ImgUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
  {
    Id: '18',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Heineken","fi":"Heineken","sv":"Heineken"}',
    Description: '{"en":"Premium lager beer - 330ml","fi":"Premium lager olut - 330ml","sv":"Premium lageröl - 330ml"}',
    Price: 5.90,
    Ingredients: '{"en":"water, barley malt, hops, yeast","fi":"vesi, ohramallas, humala, hiiva","sv":"vatten, kornmalt, humle, jäst"}',
    ImgUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
  {
    Id: '19',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"San Miguel","fi":"San Miguel","sv":"San Miguel"}',
    Description: '{"en":"Spanish premium lager - 330ml","fi":"Espanjalainen premium lager - 330ml","sv":"Spansk premium lager - 330ml"}',
    Price: 5.90,
    Ingredients: '{"en":"water, barley malt, corn, hops, yeast","fi":"vesi, ohramallas, maissi, humala, hiiva","sv":"vatten, kornmalt, majs, humle, jäst"}',
    ImgUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: true,
    Category: 3,
  },
  // Salads (Category 4)
  {
    Id: '20',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Caesar Salad","fi":"Caesar-salaatti","sv":"Caesarsallad"}',
    Description: '{"en":"Classic Caesar with crispy romaine, parmesan, and croutons","fi":"Klassinen Caesar rapean romainesalaatin, parmesaanin ja krutonkien kanssa","sv":"Klassisk Caesar med krispig romaine, parmesan och krutonger"}',
    Price: 8.99,
    Ingredients: '{"en":"romaine lettuce, parmesan cheese, croutons, Caesar dressing, lemon","fi":"romainesalaatti, parmesaani, krutonit, Caesar-kastike, sitruuna","sv":"romaine sallad, parmesanost, krutonger, Caesardressing, citron"}',
    Dietaries: [Dietary.Vegetarian],
    ImgUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 4,
  },
  {
    Id: '21',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Greek Salad","fi":"Kreikkalainen salaatti","sv":"Grekisk sallad"}',
    Description: '{"en":"Fresh vegetables with feta cheese and olives","fi":"Tuoreita vihanneksia fetajuuston ja oliivien kanssa","sv":"Färska grönsaker med fetaost och oliver"}',
    Price: 7.99,
    Ingredients: '{"en":"tomatoes, cucumber, red onion, feta cheese, olives, olive oil","fi":"tomaatit, kurkku, punainen sipuli, fetajuusto, oliivit, oliiviöljy","sv":"tomater, gurka, rödlök, fetaost, oliver, olivolja"}',
    Dietaries: [Dietary.Vegetarian, Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 4,
  },
  {
    Id: '40',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Custom Salad Bowl","fi":"Räätälöity Salaattikulho","sv":"Anpassad Salladsskål"}',
    Description: '{"en":"Build your perfect salad! Choose your base and add fresh toppings","fi":"Rakenna täydellinen salaattisi! Valitse pohja ja lisää tuoreita täytteitä","sv":"Bygg din perfekta sallad! Välj din bas och lägg till färska toppings"}',
    Price: 8.49,
    Ingredients: '{"en":"mixed greens, olive oil, lemon","fi":"sekavihreitä, oliiviöljy, sitruuna","sv":"blandade grönsaker, olivolja, citron"}',
    Dietaries: [Dietary.Vegan, Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 4,
    Toppings: '[{"Name":{"en":"Grilled Chicken","fi":"Grillattu kana","sv":"Grillad Kyckling"},"PriceIncrement":3.00},{"Name":{"en":"Grilled Shrimp","fi":"Grillatut katkaravut","sv":"Grillade Räkor"},"PriceIncrement":4.00},{"Name":{"en":"Grilled Salmon","fi":"Grillattu lohi","sv":"Grillad Lax"},"PriceIncrement":4.50},{"Name":{"en":"Tuna","fi":"Tonnikala","sv":"Tonfisk"},"PriceIncrement":3.00},{"Name":{"en":"Bacon Bits","fi":"Pekonipalat","sv":"Baconbitar"},"PriceIncrement":1.50},{"Name":{"en":"Feta Cheese","fi":"Fetajuusto","sv":"Fetaost"},"PriceIncrement":1.50},{"Name":{"en":"Parmesan Shavings","fi":"Parmesaanilastut","sv":"Parmesanskivor"},"PriceIncrement":1.50},{"Name":{"en":"Mozzarella","fi":"Mozzarella","sv":"Mozzarella"},"PriceIncrement":1.50},{"Name":{"en":"Goat Cheese","fi":"Vuohenjuusto","sv":"Getost"},"PriceIncrement":2.00},{"Name":{"en":"Cherry Tomatoes","fi":"Kirsikkatomaatit","sv":"Körsbärstomater"},"PriceIncrement":1.00},{"Name":{"en":"Cucumber","fi":"Kurkku","sv":"Gurka"},"PriceIncrement":0.75},{"Name":{"en":"Bell Peppers","fi":"Paprika","sv":"Paprika"},"PriceIncrement":1.00},{"Name":{"en":"Red Onion","fi":"Punainen sipuli","sv":"Rödlök"},"PriceIncrement":0.50},{"Name":{"en":"Avocado","fi":"Avokado","sv":"Avokado"},"PriceIncrement":2.50},{"Name":{"en":"Corn","fi":"Maissi","sv":"Majs"},"PriceIncrement":0.75},{"Name":{"en":"Black Olives","fi":"Mustat oliivit","sv":"Svarta Oliver"},"PriceIncrement":0.75},{"Name":{"en":"Walnuts","fi":"Saksanpähkinät","sv":"Valnötter"},"PriceIncrement":1.50},{"Name":{"en":"Sunflower Seeds","fi":"Auringonkukansiemenet","sv":"Solrosfrön"},"PriceIncrement":0.75},{"Name":{"en":"Croutons","fi":"Krutonit","sv":"Krutonger"},"PriceIncrement":0.75},{"Name":{"en":"Boiled Egg","fi":"Keitetty muna","sv":"Kokt Ägg"},"PriceIncrement":1.00}]',
    FreeToppings: 3,
  },
  // Pasta (Category 5)
  {
    Id: '22',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Spaghetti Carbonara","fi":"Spagetti Carbonara","sv":"Spaghetti Carbonara"}',
    Description: '{"en":"Classic Italian pasta with bacon, eggs, and parmesan","fi":"Klassinen italialainen pasta pekonin, munien ja parmesaanin kanssa","sv":"Klassisk italiensk pasta med bacon, ägg och parmesan"}',
    Price: 12.50,
    Ingredients: '{"en":"spaghetti, bacon, eggs, parmesan cheese, black pepper","fi":"spagetti, pekoni, munat, parmesaani, mustapippuri","sv":"spaghetti, bacon, ägg, parmesanost, svartpeppar"}',
    Dietaries: [],
    ImgUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 5,
  },
  {
    Id: '23',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Penne Arrabbiata","fi":"Penne Arrabbiata","sv":"Penne Arrabbiata"}',
    Description: '{"en":"Spicy tomato sauce with garlic and chili","fi":"Tulinen tomaattikastike valkosipulin ja chilin kanssa","sv":"Kryddig tomatsås med vitlök och chili"}',
    Price: 10.99,
    Ingredients: '{"en":"penne pasta, tomatoes, garlic, chili, olive oil, basil","fi":"penne-pasta, tomaatit, valkosipuli, chili, oliiviöljy, basilika","sv":"penne pasta, tomater, vitlök, chili, olivolja, basilika"}',
    Dietaries: [Dietary.Vegan],
    ImgUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 5,
  },
  {
    Id: '39',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Custom Pasta - Your Way","fi":"Räätälöity Pasta - Omalla tavallasi","sv":"Anpassad Pasta - På ditt sätt"}',
    Description: '{"en":"Choose your pasta type and build it with your favorite ingredients","fi":"Valitse pastatyyppi ja rakenna se suosikkiainesosillasi","sv":"Välj din pastatyp och bygg den med dina favoritingredienser"}',
    Price: 9.99,
    Ingredients: '{"en":"pasta, olive oil, garlic, salt","fi":"pasta, oliiviöljy, valkosipuli, suola","sv":"pasta, olivolja, vitlök, salt"}',
    Dietaries: [Dietary.Vegan],
    ImgUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 5,
    Toppings: '[{"Name":{"en":"Grilled Chicken","fi":"Grillattu kana","sv":"Grillad Kyckling"},"PriceIncrement":3.00},{"Name":{"en":"Shrimp","fi":"Katkarapu","sv":"Räkor"},"PriceIncrement":4.00},{"Name":{"en":"Bacon","fi":"Pekoni","sv":"Bacon"},"PriceIncrement":2.00},{"Name":{"en":"Italian Sausage","fi":"Italialainen makkara","sv":"Italiensk Korv"},"PriceIncrement":2.50},{"Name":{"en":"Meatballs","fi":"Lihapullat","sv":"Köttbullar"},"PriceIncrement":2.50},{"Name":{"en":"Mushrooms","fi":"Sienet","sv":"Svamp"},"PriceIncrement":1.50},{"Name":{"en":"Cherry Tomatoes","fi":"Kirsikkatomaatit","sv":"Körsbärstomater"},"PriceIncrement":1.00},{"Name":{"en":"Sun-dried Tomatoes","fi":"Auringonkuivatut tomaatit","sv":"Soltorkade Tomater"},"PriceIncrement":1.50},{"Name":{"en":"Spinach","fi":"Pinaatti","sv":"Spenat"},"PriceIncrement":1.00},{"Name":{"en":"Arugula","fi":"Rucola","sv":"Ruccola"},"PriceIncrement":1.00},{"Name":{"en":"Bell Peppers","fi":"Paprika","sv":"Paprika"},"PriceIncrement":1.00},{"Name":{"en":"Broccoli","fi":"Parsakaali","sv":"Broccoli"},"PriceIncrement":1.50},{"Name":{"en":"Zucchini","fi":"Kesäkurpitsa","sv":"Zucchini"},"PriceIncrement":1.00},{"Name":{"en":"Eggplant","fi":"Munakoiso","sv":"Aubergine"},"PriceIncrement":1.50},{"Name":{"en":"Parmesan Cheese","fi":"Parmesaani","sv":"Parmesanost"},"PriceIncrement":1.50},{"Name":{"en":"Mozzarella","fi":"Mozzarella","sv":"Mozzarella"},"PriceIncrement":1.50},{"Name":{"en":"Gorgonzola","fi":"Gorgonzola","sv":"Gorgonzola"},"PriceIncrement":2.00},{"Name":{"en":"Pesto Sauce","fi":"Pestokastike","sv":"Pestosås"},"PriceIncrement":1.50},{"Name":{"en":"Cream Sauce","fi":"Kermakastike","sv":"Gräddssås"},"PriceIncrement":1.50},{"Name":{"en":"Tomato Sauce","fi":"Tomaattikastike","sv":"Tomatsås"},"PriceIncrement":1.00}]',
    FreeToppings: 2,
  },
  // Desserts (Category 6)
  {
    Id: '24',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Tiramisu","fi":"Tiramisu","sv":"Tiramisu"}',
    Description: '{"en":"Classic Italian coffee-flavored dessert","fi":"Klassinen italialainen kahvimakuinen jälkiruoka","sv":"Klassisk italiensk dessert med kaffesmak"}',
    Price: 6.50,
    Ingredients: '{"en":"mascarpone, ladyfingers, coffee, cocoa, eggs, sugar","fi":"mascarpone, piparkakuladet, kahvi, kaakao, munat, sokeri","sv":"mascarpone, ladyfingers, kaffe, kakao, ägg, socker"}',
    Dietaries: [Dietary.Vegetarian],
    ImgUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 6,
  },
  {
    Id: '25',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Chocolate Lava Cake","fi":"Suklainen lavakakku","sv":"Chokladlavakaka"}',
    Description: '{"en":"Warm chocolate cake with molten center","fi":"Lämmin suklaakakku sulaneella keskustalla","sv":"Varm chokladkaka med smält centrum"}',
    Price: 7.50,
    Ingredients: '{"en":"chocolate, butter, eggs, sugar, flour, vanilla","fi":"suklaa, voi, munat, sokeri, jauho, vanilja","sv":"choklad, smör, ägg, socker, mjöl, vanilj"}',
    Dietaries: [Dietary.Vegetarian],
    ImgUrl: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 6,
  },
  // Seafood (Category 7)
  {
    Id: '26',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Grilled Salmon","fi":"Grillattu lohi","sv":"Grillad lax"}',
    Description: '{"en":"Fresh Atlantic salmon with lemon butter","fi":"Tuore atlantinlohi sitruunavoin kanssa","sv":"Färsk atlantlax med citronsmör"}',
    Price: 18.99,
    Ingredients: '{"en":"salmon, lemon, butter, dill, salt, pepper","fi":"lohi, sitruuna, voi, tilli, suola, pippuri","sv":"lax, citron, smör, dill, salt, peppar"}',
    Dietaries: [Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 7,
  },
  {
    Id: '27',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Fish and Chips","fi":"Kala ja perunat","sv":"Fish and chips"}',
    Description: '{"en":"Crispy battered fish with french fries","fi":"Rapea paneroitu kala ranskalaisten kanssa","sv":"Krispig friterad fisk med pommes frites"}',
    Price: 14.99,
    Ingredients: '{"en":"white fish, flour, beer, potatoes, lemon, tartar sauce","fi":"valkoinen kala, jauho, olut, perunat, sitruuna, tartarkastike","sv":"vit fisk, mjöl, öl, potatis, citron, tartarsås"}',
    Dietaries: [],
    ImgUrl: 'https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 7,
  },
  // Steaks (Category 8)
  {
    Id: '28',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Ribeye Steak","fi":"Ribeye-pihvi","sv":"Ribeye-stek"}',
    Description: '{"en":"Premium ribeye steak with garlic butter","fi":"Premium ribeye-pihvi valkosipulivoin kanssa","sv":"Premium ribeye-stek med vitlökssmör"}',
    Price: 24.99,
    Ingredients: '{"en":"beef ribeye, butter, garlic, rosemary, salt, pepper","fi":"naudanlihan ribeye, voi, valkosipuli, rosmariini, suola, pippuri","sv":"nötkött ribeye, smör, vitlök, rosmarin, salt, peppar"}',
    Dietaries: [Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 8,
  },
  {
    Id: '29',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Sirloin Steak","fi":"Paahtopaisti","sv":"Sirloin-stek"}',
    Description: '{"en":"Tender sirloin with peppercorn sauce","fi":"Murea paahtopaisti pippurikastikkeella","sv":"Mör sirloin med pepparsås"}',
    Price: 21.99,
    Ingredients: '{"en":"beef sirloin, peppercorns, cream, brandy, salt","fi":"naudanlihan paahtopaisti, pippurit, kerma, konjakki, suola","sv":"nötkött sirloin, peppar, grädde, konjak, salt"}',
    Dietaries: [Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 8,
  },
  // Chicken (Category 9)
  {
    Id: '30',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Grilled Chicken Breast","fi":"Grillattu kananrinta","sv":"Grillad kycklingbröst"}',
    Description: '{"en":"Herb-marinated grilled chicken","fi":"Yrtti-marinoitu grillattu kana","sv":"Örtmarinerad grillad kyckling"}',
    Price: 13.99,
    Ingredients: '{"en":"chicken breast, herbs, olive oil, lemon, garlic","fi":"kananrinta, yrtit, oliiviöljy, sitruuna, valkosipuli","sv":"kycklingbröst, örter, olivolja, citron, vitlök"}',
    Dietaries: [Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 9,
  },
  {
    Id: '31',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Chicken Wings","fi":"Kanan siivet","sv":"Kycklingvingar"}',
    Description: '{"en":"Crispy chicken wings with spicy sauce","fi":"Rapeat kanan siivet tulisen kastikkeen kanssa","sv":"Krispiga kycklingvingar med stark sås"}',
    Price: 10.99,
    Ingredients: '{"en":"chicken wings, hot sauce, butter, celery, blue cheese","fi":"kanan siivet, tulinen kastike, voi, selleri, sinihomejuusto","sv":"kycklingvingar, het sås, smör, selleri, blåmögelost"}',
    Dietaries: [Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 9,
  },
  // Breakfast (Category 10)
  {
    Id: '32',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Full English Breakfast","fi":"Täysi englantilainen aamiainen","sv":"Fullständig engelsk frukost"}',
    Description: '{"en":"Eggs, bacon, sausage, beans, toast, and tomatoes","fi":"Munat, pekoni, makkara, pavut, paahtoleipä ja tomaatit","sv":"Ägg, bacon, korv, bönor, rostat bröd och tomater"}',
    Price: 11.99,
    Ingredients: '{"en":"eggs, bacon, sausage, baked beans, bread, tomatoes, mushrooms","fi":"munat, pekoni, makkara, paistetut pavut, leipä, tomaatit, sienet","sv":"ägg, bacon, korv, bakade bönor, bröd, tomater, svamp"}',
    Dietaries: [],
    ImgUrl: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 10,
  },
  {
    Id: '33',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Pancakes","fi":"Pannukakut","sv":"Pannkakor"}',
    Description: '{"en":"Fluffy pancakes with maple syrup and berries","fi":"Pörröiset pannukakut vaahterasiirapilla ja marjoilla","sv":"Fluffiga pannkakor med lönnsirap och bär"}',
    Price: 8.99,
    Ingredients: '{"en":"flour, eggs, milk, butter, maple syrup, berries","fi":"jauho, munat, maito, voi, vaahterasiirappi, marjat","sv":"mjöl, ägg, mjölk, smör, lönnsirap, bär"}',
    Dietaries: [Dietary.Vegetarian],
    ImgUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 10,
  },
  // Soups (Category 11)
  {
    Id: '34',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Tomato Soup","fi":"Tomaattikeitto","sv":"Tomatsoppa"}',
    Description: '{"en":"Creamy tomato soup with fresh basil","fi":"Kermainen tomaattikeitto tuoreella basilikalla","sv":"Krämig tomatsoppa med färsk basilika"}',
    Price: 6.99,
    Ingredients: '{"en":"tomatoes, cream, basil, garlic, onion, vegetable broth","fi":"tomaatit, kerma, basilika, valkosipuli, sipuli, kasvisliemi","sv":"tomater, grädde, basilika, vitlök, lök, grönsaksbuljong"}',
    Dietaries: [Dietary.Vegetarian, Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 11,
  },
  {
    Id: '35',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Mushroom Soup","fi":"Sienisoppa","sv":"Svampsoppa"}',
    Description: '{"en":"Rich and creamy mushroom soup","fi":"Rikas ja kermainen sienisoppa","sv":"Rik och krämig svampsoppa"}',
    Price: 7.50,
    Ingredients: '{"en":"mushrooms, cream, butter, thyme, garlic, vegetable broth","fi":"sienet, kerma, voi, timjami, valkosipuli, kasvisliemi","sv":"svamp, grädde, smör, timjan, vitlök, grönsaksbuljong"}',
    Dietaries: [Dietary.Vegetarian, Dietary.GlutenFree],
    ImgUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 11,
  },
  // Wraps (Category 12)
  {
    Id: '36',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Chicken Wrap","fi":"Kana-tortilla","sv":"Kycklingrulle"}',
    Description: '{"en":"Grilled chicken with fresh vegetables in a tortilla","fi":"Grillattu kana tuoreiden vihannesten kanssa tortillassa","sv":"Grillad kyckling med färska grönsaker i tortilla"}',
    Price: 9.99,
    Ingredients: '{"en":"tortilla, chicken, lettuce, tomato, cucumber, sauce","fi":"tortilla, kana, salaatti, tomaatti, kurkku, kastike","sv":"tortilla, kyckling, sallad, tomat, gurka, sås"}',
    Dietaries: [],
    ImgUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 12,
  },
  {
    Id: '37',
    OrganizationId: 'mock-org-1',
    Name: '{"en":"Veggie Wrap","fi":"Kasvis-tortilla","sv":"Vegetarisk rulle"}',
    Description: '{"en":"Fresh vegetables and hummus in a whole wheat tortilla","fi":"Tuoreet vihannekset ja hummus täysjyvätortillassa","sv":"Färska grönsaker och hummus i fullkornstortilla"}',
    Price: 8.49,
    Ingredients: '{"en":"whole wheat tortilla, hummus, lettuce, tomato, cucumber, carrot, bell pepper","fi":"täysjyvätortilla, hummus, salaatti, tomaatti, kurkku, porkkana, paprika","sv":"fullkornstortilla, hummus, sallad, tomat, gurka, morot, paprika"}',
    Dietaries: [Dietary.Vegan],
    ImgUrl: 'https://images.unsplash.com/photo-1592415486689-125cbbfcbee2?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 12,
  },
];

// Base categories
export const MOCK_CATEGORIES = [
  '{"en":"Pizzas","fi":"Pizzat","sv":"Pizzor"}',
  '{"en":"Burgers","fi":"Hampurilaiset","sv":"Hamburgare"}',
  '{"en":"Sides","fi":"Lisukkeet","sv":"Tillbehör"}',
  '{"en":"Drinks","fi":"Juomat","sv":"Drycker"}',
  '{"en":"Salads","fi":"Salaatit","sv":"Sallader"}',
  '{"en":"Pasta","fi":"Pastat","sv":"Pasta"}',
  '{"en":"Desserts","fi":"Jälkiruoat","sv":"Desserter"}',
  '{"en":"Seafood","fi":"Kala ja merenelävät","sv":"Skaldjur"}',
  '{"en":"Steaks","fi":"Pihvit","sv":"Stekar"}',
  '{"en":"Chicken","fi":"Kanaruoat","sv":"Kycklingrätter"}',
  '{"en":"Breakfast","fi":"Aamiainen","sv":"Frukost"}',
  '{"en":"Soups","fi":"Keitot","sv":"Soppor"}',
  '{"en":"Wraps & Sandwiches","fi":"Tortillat ja voileivät","sv":"Wraps & Smörgåsar"}',
];
