import type { Product } from '../types';

// Extended Product type with category for menu display
export interface ProductWithCategory extends Product {
  Category: number;
}

// Mock product data - this will be replaced with real API data later
export const MOCK_PRODUCTS: ProductWithCategory[] = [
  // Pizzas (Category 0)
  {
    Id: '1',
    OrganizationId: 'mock-org-1',
    Name: 'Margherita Pizza',
    Description: 'Classic pizza with tomato sauce, mozzarella, and fresh basil',
    Price: 12.99,
    ImgUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
  },
  {
    Id: '2',
    OrganizationId: 'mock-org-1',
    Name: 'Pepperoni Pizza',
    Description: 'Pizza topped with spicy pepperoni and mozzarella cheese',
    Price: 14.99,
    ImgUrl: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
  },
  {
    Id: '3',
    OrganizationId: 'mock-org-1',
    Name: 'Hawaiian Pizza',
    Description: 'Pizza with ham, pineapple, and mozzarella',
    Price: 13.99,
    ImgUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
  },
  {
    Id: '4',
    OrganizationId: 'mock-org-1',
    Name: 'Veggie Supreme',
    Description: 'Loaded with fresh vegetables and mozzarella',
    Price: 13.49,
    ImgUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
  },
  {
    Id: '5',
    OrganizationId: 'mock-org-1',
    Name: 'BBQ Chicken',
    Description: 'BBQ sauce, grilled chicken, red onions, and cilantro',
    Price: 15.99,
    ImgUrl: 'https://images.unsplash.com/photo-1595854341625-f33ee10dbf94?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
  },
  {
    Id: '6',
    OrganizationId: 'mock-org-1',
    Name: 'Meat Lovers',
    Description: 'Loaded with pepperoni, sausage, ham, and bacon',
    Price: 16.99,
    ImgUrl: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 0,
  },
  // Burgers (Category 1)
  {
    Id: '7',
    OrganizationId: 'mock-org-1',
    Name: 'Classic Burger',
    Description: 'Beef patty with lettuce, tomato, onion, and pickles',
    Price: 9.99,
    ImgUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
  },
  {
    Id: '8',
    OrganizationId: 'mock-org-1',
    Name: 'Cheese Burger',
    Description: 'Double beef patty with melted cheese',
    Price: 10.99,
    ImgUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
  },
  {
    Id: '9',
    OrganizationId: 'mock-org-1',
    Name: 'Bacon Burger',
    Description: 'Burger with crispy bacon and BBQ sauce',
    Price: 11.99,
    ImgUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 1,
  },
  // Sides (Category 2)
  {
    Id: '10',
    OrganizationId: 'mock-org-1',
    Name: 'French Fries',
    Description: 'Crispy golden french fries',
    Price: 4.99,
    ImgUrl: 'https://images.unsplash.com/photo-1630384082554-e4e5c0e7b869?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
  },
  {
    Id: '11',
    OrganizationId: 'mock-org-1',
    Name: 'Onion Rings',
    Description: 'Crispy breaded onion rings',
    Price: 5.49,
    ImgUrl: 'https://images.unsplash.com/photo-1619221882783-4f9a5e2e3ee9?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
  },
  {
    Id: '12',
    OrganizationId: 'mock-org-1',
    Name: 'Mozzarella Sticks',
    Description: 'Breaded mozzarella sticks with marinara sauce',
    Price: 6.99,
    ImgUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 2,
  },
  // Drinks (Category 3)
  {
    Id: '13',
    OrganizationId: 'mock-org-1',
    Name: 'Coca-Cola',
    Description: 'Classic Coca-Cola',
    Price: 2.99,
    ImgUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  {
    Id: '14',
    OrganizationId: 'mock-org-1',
    Name: 'Sprite',
    Description: 'Refreshing lemon-lime soda',
    Price: 2.99,
    ImgUrl: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
  {
    Id: '15',
    OrganizationId: 'mock-org-1',
    Name: 'Orange Juice',
    Description: 'Fresh squeezed orange juice',
    Price: 3.49,
    ImgUrl: 'https://images.unsplash.com/photo-1560512823-829485b8bf24?w=400',
    Enabled: true,
    Created: new Date(),
    AgeRestrictied: false,
    Category: 3,
  },
];

// Base categories
export const MOCK_CATEGORIES = ['Pizzas', 'Burgers', 'Sides', 'Drinks'];
